name: tests

on:
  push:
    branches: ['**']

jobs:
  test:
    if: github.repository == 'plughacker/malga-tokenization'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3.0.0
        with:
          run_install: true
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit and integration tests
        run: pnpm test:ci
